import Head from "next/head";
import { useAppDispatch, useAppSelector } from "@/redux/hooks";
import { useGetCarDetailsQuery } from "@/redux/api/carApi";
import { changeCurrIndex } from "@/redux/slices/carSlice";

export default function Home() {
  const { data, error, isLoading, isError } = useGetCarDetailsQuery({
    limit: "10",
    page: "0",
  });
  const currIndex = useAppSelector((state) => state.cars.currIndex);
  const dispatch = useAppDispatch();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {isLoading ? (
          <>Loading...</>
        ) : isError ? (
          <>Error</>
        ) : (
          <main >
            <div>
              {data?.map((item: any, id: any) => {
                return (
                  <div
                    key={id}
                    onClick={() =>
                      dispatch(changeCurrIndex(data.indexOf(item)))
                    }
                  >
                    {item.model}
                    <div
                    >
                      <div>
                        {data?.[currIndex]?.model} - {data?.[currIndex]?.year}
                      </div>
                      <div>
                        {data?.[currIndex]?.make} - {data?.[currIndex]?.type}
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </main>
        )}
      </>
    </>
  );
}